apiVersion: servicecatalog.k8s.io/v1beta1
kind: ServiceInstance
metadata:
  name: rds-mysql-instance
  namespace: test-ns
spec:
  clusterServiceClassExternalName: mysql
  clusterServicePlanExternalName: default
  parameters:
    mysqlDatabase: mysqldb
    mysqlUser: admin
    mysqlPassword: changeme
    persistence:
      enabled: false
