apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: wordpress
spec:
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - name: wordpress
        image: "bitnami/wordpress:latest"
        env:
        - name: MARIADB_HOST
          valueFrom:
            secretKeyRef:
              name: mariadb-instance-credentials
              key: host
        - name: MARIADB_PORT
          valueFrom:
            secretKeyRef:
              name: mariadb-instance-credentials
              key: port
        - name: WORDPRESS_DATABASE_USER
          valueFrom:
            secretKeyRef:
              name: mariadb-instance-credentials
              key: username
        - name: WORDPRESS_DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mariadb-instance-credentials
              key: password
        - name: WORDPRESS_DATABASE_NAME
          valueFrom:
            secretKeyRef:
              name: mariadb-instance-credentials
              key: database
        ports:
        - name: http
          containerPort: 80
        livenessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 120
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 5
          timeoutSeconds: 1
---
apiVersion: v1
kind: Service
metadata:
  name: wordpress
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    targetPort: http
  selector:
    app: wordpress
